N = int(input()) #1329(input)
years = int(N/365)
a = str(years)
remaining = int(N%365)
weeks = int(remaining/7)
b = str(weeks)
days = int(remaining%7)
c = str(days)
print(a+" years "+b+" weeks " +c+" days ")